services:
  backend:
    volumes:
      - ./chatapp_django:/app
    build: ./chatapp_django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6397"
