services:
  backend:

    volumes:
      - ./chatapp_django/chat/migrations:/app/chat/migrations
    build: ./chatapp_django
    command: python manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action : sync
          path: ./chatapp_django
          target: /app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always
